import type { TourPackage } from '~/types/package'

export const FALLBACK_PACKAGES: TourPackage[] = [
  {
    id: 1,
    title: 'クラシック・パリ入門',
    slug: 'classic-paris-essentials',
    summary: 'ルーヴルの朝、シテ島、セーヌ河畔で過ごすゆとりの午後。',
    description:
      '慌ただしさのない3日間。時間指定のルーヴル入場、シテ島とノートルダム周辺のガイド散策、河畔カフェでの休息も。初めてのパリでも心地よく巡れます。',
    destination: 'ルーヴル＆シテ島',
    region: 'パリ',
    durationDays: 3,
    priceFrom: 890,
    currency: 'EUR',
    featured: true,
    bookingUnlimited: false,
    slotsTotal: 10,
    slotsSold: 0,
    available: 10,
    soldOut: false,
    difficulty: 'easy',
    highlights: ['ルーヴル時間指定入場', 'シテ島ウォーキング', 'セーヌ河畔カフェ'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 2,
    title: 'モンマルトル・アフターダーク',
    slug: 'montmartre-after-dark',
    summary: '村のような路地、サクレ・クールの夕景、屋上からの夜景ディナー。',
    description:
      'モンマルトルの静かな路地をたそがれに歩くプラン。サクレ・クールのゴールデンアワー、その後はパリの屋根を望むディナー。',
    destination: 'モンマルトル',
    region: 'パリ',
    durationDays: 1,
    priceFrom: 280,
    currency: 'EUR',
    featured: true,
    bookingUnlimited: false,
    slotsTotal: 10,
    slotsSold: 0,
    available: 10,
    soldOut: false,
    difficulty: 'easy',
    highlights: ['サクレ・クール夕景', '隠れた階段散策', '屋上ディナー'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 3,
    title: 'マレ地区プライベートウォーク',
    slug: 'le-marais-private-walk',
    summary: 'オテル・パルティキュリエ、ヴォージュ広場、話題のスイーツ巡り。',
    description:
      'マレ地区を半日プライベートガイド。普段は立ち入れない中庭、アーケードのヴォージュ広場、地元おすすめの試食スポットへ。',
    destination: 'マレ地区',
    region: 'パリ',
    durationDays: 1,
    priceFrom: 195,
    currency: 'EUR',
    featured: true,
    bookingUnlimited: false,
    slotsTotal: 10,
    slotsSold: 0,
    available: 10,
    soldOut: false,
    difficulty: 'easy',
    highlights: ['ヴォージュ広場', '中庭アクセス', 'スイーツ＆ファラフェル'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1550340499-a6c60fc8287c?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 4,
    title: 'ヴェルサイユ・ロイヤルデー',
    slug: 'versailles-royal-day',
    summary: '宮殿・庭園・トリアノン。パリ市内からの往復送迎付き。',
    description:
      'スキップ・ザ・ラインで宮殿へ。庭園ガイド、マリー・アントワネットの集落で自由時間。パリからの送迎込み。',
    destination: 'ヴェルサイユ',
    region: 'パリ',
    durationDays: 1,
    priceFrom: 245,
    currency: 'EUR',
    featured: false,
    bookingUnlimited: false,
    slotsTotal: 10,
    slotsSold: 0,
    available: 10,
    soldOut: false,
    difficulty: 'moderate',
    highlights: ['優先入場', '庭園＆トリアノン', 'パリ送迎'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1549144511-94b4f76f4cce?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 5,
    title: '左岸文学散策',
    slug: 'left-bank-literary-trail',
    summary: 'サン＝ジェルマンの本屋、カフェ文化、黄昏のリュクサンブール。',
    description:
      'シェイクスピア・アンド・カンパニー、サン＝ジェルマンのカフェ、リュクサンブール公園をゆるやかに巡ります。',
    destination: 'サン＝ジェルマン＆カルチエ・ラタン',
    region: 'パリ',
    durationDays: 1,
    priceFrom: 165,
    currency: 'EUR',
    featured: false,
    bookingUnlimited: false,
    slotsTotal: 10,
    slotsSold: 0,
    available: 10,
    soldOut: false,
    difficulty: 'easy',
    highlights: ['シェイクスピア・アンド・カンパニー', 'カフェテラス', 'リュクサンブール公園'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1522093007474-d8631f559f6f?auto=format&fit=crop&w=1600&q=80',
  },
  {
    id: 6,
    title: 'セーヌ夕暮れクルーズ',
    slug: 'seine-twilight-cruise',
    summary: 'エッフェル塔、オルセー、ノートルダムを川から眺める夜。',
    description:
      '夕暮れの乗船。船上シャンパン、川面からの名所巡り。その後、河岸ディナーもオプションで。',
    destination: 'セーヌ川',
    region: 'パリ',
    durationDays: 1,
    priceFrom: 320,
    currency: 'EUR',
    featured: false,
    bookingUnlimited: false,
    slotsTotal: 10,
    slotsSold: 0,
    available: 10,
    soldOut: false,
    difficulty: 'easy',
    highlights: ['夕暮れ出発', '船上シャンパン', '河岸ディナー（任意）'],
    heroImageUrl:
      'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?auto=format&fit=crop&w=1600&q=80',
  },
]
